version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    # hostname required for mounted data
    hostname: klips-rabbit
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq:Z
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  dispatcher:
    image: ghcr.io/klips-project/mqm-worker/dispatcher
    depends_on:
        - rabbitmq
    environment:
      - RABBITHOST=rabbitmq
      - RABBITUSER=${RABBITMQ_DEFAULT_USER}
      - RABBITPASS=${RABBITMQ_DEFAULT_PASS}
      - WORKERQUEUE=dispatcher
      - RESULTSQUEUE=results

  postgres:
    image: postgis/postgis:13-3.1-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
