version: '3'

volumes:
    tmp-data:

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    # hostname required for mounted data
    hostname: ${RABBITMQ_HOSTNAME}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq:Z
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  dispatcher:
    image: ghcr.io/klips-project/mqm-worker/dispatcher:latest
    restart: unless-stopped
    depends_on:
        - rabbitmq
    environment:
      - RABBITHOST=${RABBITMQ_HOSTNAME}
      - RABBITUSER=${RABBITMQ_DEFAULT_USER}
      - RABBITPASS=${RABBITMQ_DEFAULT_PASS}
      - RESULTSQUEUE=${RABBITMQ_RESULTSQUEUE}
      - WORKERQUEUE=dispatcher

  worker-geoserver-publish-geotiff:
    image: ghcr.io/klips-project/mqm-worker/geoserver-publish-geotiff:latest
    restart: unless-stopped
    volumes:
      - tmp-data:/home/data:Z
    depends_on:
      - rabbitmq
    environment:
    - RABBITHOST=${RABBITMQ_HOSTNAME}
    - RABBITUSER=${RABBITMQ_DEFAULT_USER}
    - RABBITPASS=${RABBITMQ_DEFAULT_PASS}
    - RESULTSQUEUE=${RABBITMQ_RESULTSQUEUE}
    - WORKERQUEUE=geoserver-publish-geotiff
    - GEOSERVER_REST_URL=http://${GEOSERVER_HOSTNAME}:8080/geoserver/rest/
    - GEOSERVER_USER=${GEOSERVER_USER}
    - GEOSERVER_PASSWORD=${GEOSERVER_PASSWORD}

  worker-download:
    image: ghcr.io/klips-project/mqm-worker/download-new-data-from-url:latest
    restart: unless-stopped
    volumes:
      - tmp-data:/home/data:Z
    depends_on:
      - rabbitmq
    environment:
      - RABBITHOST=${RABBITMQ_HOSTNAME}
      - RABBITUSER=${RABBITMQ_DEFAULT_USER}
      - RABBITPASS=${RABBITMQ_DEFAULT_PASS}
      - RESULTSQUEUE=${RABBITMQ_RESULTSQUEUE}
      - WORKERQUEUE=download

  geoserver:
    image: meggsimum/geoserver:2.20.2
    hostname: ${GEOSERVER_HOSTNAME}
    ports:
     - 8080:8080
    volumes:
      - ./geoserver_data:/opt/geoserver_data/:Z
    environment:
      - EXTRA_JAVA_OPTS=-Xms1g -Xmx2g
      - USE_VECTOR_TILES=0
      - USE_CORS=0

  geoserver-init:
    build: ./geoserver-init
    depends_on:
        - geoserver
    environment:
        - GEOSERVER_REST_URL=http://${GEOSERVER_HOSTNAME}:8080/geoserver/rest/
    command: [ "./wait-for.sh", "${GEOSERVER_HOSTNAME}:8080", "--", "npm", "run", "start"]

  # only needed for development, it mocks a webspace where data can be loaded from
  nginx:
    image: nginx
    volumes:
      - ./mocked-webspace:/usr/share/nginx/html:ro

  # Not needed at the moment

  # postgres:
  #   image: postgis/postgis:13-3.1-alpine
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
